### ISSUE TITLE
Can't use vgpu in vm

### ISSUE THREAD

**Issue by cdm1993dk** [tenclass/mvisor-win-vgpu-driver#1]
Hi, I have installed the driver in a win10 vm, but gputest showed nothing during the test: 
![1](https://github.com/tenclass/mvisor-win-vgpu-driver/assets/144340336/55e781ec-215c-4055-a1ab-e98c3fc674d8)
![3](https://github.com/tenclass/mvisor-win-vgpu-driver/assets/144340336/dab88bd9-ca5b-41e5-94f9-646c6d19d90d)

From the mvisor's log, it seems that the commands sent from vgpu had reached virglrenderer, but virglrenderer failed to render it correctly: 
![2](https://github.com/tenclass/mvisor-win-vgpu-driver/assets/144340336/c4b3ae92-2932-4fc1-8d62-cf431dfa5403)

There is a gtx1650 on the host which has the latest proprietary NVIDIA driver installed. Some env info :
- os: centos 8
- mvisor: compiled from source 
- vgpu driver: 1.0.0
- virglrender: 0.10.4

vgpu config:

```
  - class: virtio-vgpu
    memory: 1G
    staging: Yes
    blob: Yes
    node: /dev/dri/renderD128

```

Any suggestions?

**Comment by nooodles2023** [comment]
oh, there are something wrong with virglrender, have you ever try to build virglrender from source?

**Comment by cdm1993dk** [comment]
I use the virglrender built from source and now it's working, thx!
