### ISSUE TITLE
Failed to compile mvisor-win-vgpu-driver.

### ISSUE THREAD

**Issue by wangzh21** [tenclass/mvisor-win-vgpu-driver#3]
Hi team,
   I'd like to compile vgpu-driver by myself. I built driver with command `build.bat C:\mvisor-win-vgpu-driver\usermode`. But it failed with:
   C:\mvisor-win-vgpu-driver\usermode\mesa\src\gallium\winsys\virgl\drm\virgl_drm_winsys.h(82): error C2099: initializer is not a constant

Here is my env info:
python 3.12.0
Microsoft Visual Studio Community 2019  16.11.31
cmake version 3.28.0-rc3
meson 1.2.3

Are there any suggestions?

Thx.

**Comment by nooodles2023** [comment]
It's just a compiler error, which compiler did you use, MSVC or GCC?

**Comment by wangzh21** [comment]
It is clang, should I use MSVC or GCC?  Could you share your compiler version information?

**Comment by nooodles2023** [comment]
> It is clang, should I use MSVC or GCC? Could you share your compiler version information?

gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

**Comment by wangzh21** [comment]
> > It is clang, should I use MSVC or GCC? Could you share your compiler version information?
> 
> gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

Cool, it worked well. Thx a lot.
