### ISSUE TITLE
Need some guidance to compile

### ISSUE THREAD

**Issue by Gargazou** [tenclass/mvisor-win-vgpu-driver#6]
I am trying to compile this code.  Unfortunately, I ran into a series of issues.
Is there some specific flags, packages, libraries or settings to use to compile using VS2019?
 
**Here is my environment.**
- Windows 10,  v1809
  - VS2019.  In the VS installer, I selected:
  - Python (Python 3, 64 bits v3.9.3
  - Desktop development with C++, including all Win10 SDK
- Install dependencies: py -3 -m pip install meson packaging mako
- Set System PATH to point to meson.exe
- Installed Win-flex-bison in C:\Program Files\win_flex_bison + added the path
-Downloaded the Windows Driver development kit for VS2019, Win10 1809.
-Installed Git, 
-Downloaded the mvisor-win-vgpu-driver-master.zip and extract

**Steps to reproduce:**
Open a native VS2019 Shell x64.
cd into mvisor-win-vgpu-driver-master\usermode
build.bat d:\mesa

**Compilation output (with errors):**
   Creating library subprojects\zlib-1.2.13\z.lib and object subprojects\zlib-1.2.13\z.exp
[862/905] Compiling C object src/gallium/drivers/virgl/libvirgl.a.p/virgl_context.c.obj
FAILED: src/gallium/drivers/virgl/libvirgl.a.p/virgl_context.c.obj
"cl" "-Isrc\gallium\drivers/virgl\libvirgl.a.p" "-Isrc\gallium\drivers/virgl" "-I..\src\gallium\drivers\virgl" "-Iinclude" "-I..\include" "-Isrc" "-I..\src" "-Isrc\mapi" "-I..\src\mapi" "-Isrc\mesa" "-I..\src\mesa" "-I..\src\gallium\include" "-Isrc\gallium\auxiliary" "-I..\src\gallium\auxiliary" "-Isrc\virtio" "-I..\src\virtio" "-Isubprojects\zlib-1.2.13" "-I..\subprojects\zlib-1.2.13" "-Isrc\compiler\nir" "-I..\src\compiler\nir" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/std:c11" "/O2" "/Gw" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DPACKAGE_VERSION=\"23.1.0-devel\"" "-DPACKAGE_BUGREPORT=\"https://gitlab.freedesktop.org/mesa/mesa/-/issues\"" "-DHAVE_OPENGL=1" "-DHAVE_OPENGL_ES_1=0" "-DHAVE_OPENGL_ES_2=0" "-DHAVE_VIRGL" "-DVIDEO_CODEC_VC1DEC=0" "-DVIDEO_CODEC_H264DEC=0" "-DVIDEO_CODEC_H264ENC=0" "-DVIDEO_CODEC_H265DEC=0" "-DVIDEO_CODEC_H265ENC=0" "-DHAVE_WINDOWS_PLATFORM" "-DENABLE_ST_OMX_BELLAGIO=0" "-DENABLE_ST_OMX_TIZONIA=0" "-DALLOW_KCMP" "-D_WINDOWS" "-D_WIN32_WINNT=0x0A00" "-DWINVER=0x0A00" "-DPIPE_SUBSYSTEM_WINDOWS_USER" "-D_USE_MATH_DEFINES" "-DVC_EXTRALEAN" "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_SECURE_NO_DEPRECATE" "-D_SCL_SECURE_NO_WARNINGS" "-D_SCL_SECURE_NO_DEPRECATE" "-D_ALLOW_KEYWORD_MACROS" "-D_HAS_EXCEPTIONS=0" "-DNOMINMAX" "-DUSE_SSE41" "-DMISSING_64BIT_ATOMICS" "-DHAVE_STRTOF" "-DHAVE_TIMESPEC_GET" "-DHAVE_QSORT_S" "-DHAVE_STRUCT_TIMESPEC" "-DHAVE_ZLIB" "-DHAVE_COMPRESSION" "-DWIN32_LEAN_AND_MEAN" "-DMESA_EXECMEM" "/wd4018" "/wd4056" "/wd4244" "/wd4267" "/wd4305" "/wd4351" "/wd4756" "/wd4800" "/wd4996" "/wd4291" "/wd4146" "/wd4200" "/wd4624" "/wd4309" "/wd4838" "/wd5105" "/we4020" "/we4024" "/we4189" "/Zc:__cplusplus" "-DNO_REGEX" "/Fdsrc\gallium\drivers/virgl\libvirgl.a.p\virgl_context.c.pdb" /Fosrc/gallium/drivers/virgl/libvirgl.a.p/virgl_context.c.obj "/c" ../src/gallium/drivers/virgl/virgl_context.c
../src/gallium/drivers/virgl/virgl_context.c(412): warning C4312: 'type cast': conversion from 'unsigned long' to 'void *' of greater size
../src/gallium/drivers/virgl/virgl_context.c(420): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(428): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(440): warning C4312: 'type cast': conversion from 'unsigned long' to 'void *' of greater size
../src/gallium/drivers/virgl/virgl_context.c(447): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(455): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(773): warning C4312: 'type cast': conversion from 'unsigned long' to 'void *' of greater size
../src/gallium/drivers/virgl/virgl_context.c(810): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(820): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(830): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(840): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(850): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(859): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(868): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(877): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(886): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(896): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(963): error C2059: syntax error: '}'
../src/gallium/drivers/virgl/virgl_context.c(1168): warning C4312: 'type cast': conversion from 'unsigned long' to 'void *' of greater size
../src/gallium/drivers/virgl/virgl_context.c(1175): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(1190): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(1445): error C2059: syntax error: '}'
../src/gallium/drivers/virgl/virgl_context.c(1476): warning C4312: 'type cast': conversion from 'unsigned long' to 'void *' of greater size
../src/gallium/drivers/virgl/virgl_context.c(1481): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(1489): warning C4311: 'type cast': pointer truncation from 'void *' to 'unsigned long'
../src/gallium/drivers/virgl/virgl_context.c(1701): warning C4028: formal parameter 3 different from declaration
[863/905] Compiling C object src/gallium/drivers/virgl/libvirgl.a.p/virgl_resource.c.obj
FAILED: src/gallium/drivers/virgl/libvirgl.a.p/virgl_resource.c.obj
"cl" "-Isrc\gallium\drivers/virgl\libvirgl.a.p" "-Isrc\gallium\drivers/virgl" "-I..\src\gallium\drivers\virgl" "-Iinclude" "-I..\include" "-Isrc" "-I..\src" "-Isrc\mapi" "-I..\src\mapi" "-Isrc\mesa" "-I..\src\mesa" "-I..\src\gallium\include" "-Isrc\gallium\auxiliary" "-I..\src\gallium\auxiliary" "-Isrc\virtio" "-I..\src\virtio" "-Isubprojects\zlib-1.2.13" "-I..\subprojects\zlib-1.2.13" "-Isrc\compiler\nir" "-I..\src\compiler\nir" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/std:c11" "/O2" "/Gw" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DPACKAGE_VERSION=\"23.1.0-devel\"" "-DPACKAGE_BUGREPORT=\"https://gitlab.freedesktop.org/mesa/mesa/-/issues\"" "-DHAVE_OPENGL=1" "-DHAVE_OPENGL_ES_1=0" "-DHAVE_OPENGL_ES_2=0" "-DHAVE_VIRGL" "-DVIDEO_CODEC_VC1DEC=0" "-DVIDEO_CODEC_H264DEC=0" "-DVIDEO_CODEC_H264ENC=0" "-DVIDEO_CODEC_H265DEC=0" "-DVIDEO_CODEC_H265ENC=0" "-DHAVE_WINDOWS_PLATFORM" "-DENABLE_ST_OMX_BELLAGIO=0" "-DENABLE_ST_OMX_TIZONIA=0" "-DALLOW_KCMP" "-D_WINDOWS" "-D_WIN32_WINNT=0x0A00" "-DWINVER=0x0A00" "-DPIPE_SUBSYSTEM_WINDOWS_USER" "-D_USE_MATH_DEFINES" "-DVC_EXTRALEAN" "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_SECURE_NO_DEPRECATE" "-D_SCL_SECURE_NO_WARNINGS" "-D_SCL_SECURE_NO_DEPRECATE" "-D_ALLOW_KEYWORD_MACROS" "-D_HAS_EXCEPTIONS=0" "-DNOMINMAX" "-DUSE_SSE41" "-DMISSING_64BIT_ATOMICS" "-DHAVE_STRTOF" "-DHAVE_TIMESPEC_GET" "-DHAVE_QSORT_S" "-DHAVE_STRUCT_TIMESPEC" "-DHAVE_ZLIB" "-DHAVE_COMPRESSION" "-DWIN32_LEAN_AND_MEAN" "-DMESA_EXECMEM" "/wd4018" "/wd4056" "/wd4244" "/wd4267" "/wd4305" "/wd4351" "/wd4756" "/wd4800" "/wd4996" "/wd4291" "/wd4146" "/wd4200" "/wd4624" "/wd4309" "/wd4838" "/wd5105" "/we4020" "/we4024" "/we4189" "/Zc:__cplusplus" "-DNO_REGEX" "/Fdsrc\gallium\drivers/virgl\libvirgl.a.p\virgl_resource.c.pdb" /Fosrc/gallium/drivers/virgl/libvirgl.a.p/virgl_resource.c.obj "/c" ../src/gallium/drivers/virgl/virgl_resource.c
../src/gallium/drivers/virgl/virgl_resource.c(396): error C2036: 'void *': unknown size
../src/gallium/drivers/virgl/virgl_resource.c(539): error C2036: 'void *': unknown size
[864/905] Compiling C object src/gallium/winsys/virgl/lib/libvgpu_api.a.p/vgpu_api.c.obj
FAILED: src/gallium/winsys/virgl/lib/libvgpu_api.a.p/vgpu_api.c.obj
"cl" "-Isrc\gallium\winsys/virgl/lib\libvgpu_api.a.p" "-Isrc\gallium\winsys/virgl/lib" "-I..\src\gallium\winsys\virgl\lib" "-Iinclude" "-I..\include" "-Isrc" "-I..\src" "-Isrc\mapi" "-I..\src\mapi" "-Isrc\mesa" "-I..\src\mesa" "-I..\src\gallium\include" "-Isrc\gallium\auxiliary" "-I..\src\gallium\auxiliary" "-Isrc\gallium\drivers" "-I..\src\gallium\drivers" "-Isrc\virtio" "-I..\src\virtio" "-Isubprojects\zlib-1.2.13" "-I..\subprojects\zlib-1.2.13" "-Isrc\compiler\nir" "-I..\src\compiler\nir" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/std:c11" "/O2" "/Gw" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DPACKAGE_VERSION=\"23.1.0-devel\"" "-DPACKAGE_BUGREPORT=\"https://gitlab.freedesktop.org/mesa/mesa/-/issues\"" "-DHAVE_OPENGL=1" "-DHAVE_OPENGL_ES_1=0" "-DHAVE_OPENGL_ES_2=0" "-DHAVE_VIRGL" "-DVIDEO_CODEC_VC1DEC=0" "-DVIDEO_CODEC_H264DEC=0" "-DVIDEO_CODEC_H264ENC=0" "-DVIDEO_CODEC_H265DEC=0" "-DVIDEO_CODEC_H265ENC=0" "-DHAVE_WINDOWS_PLATFORM" "-DENABLE_ST_OMX_BELLAGIO=0" "-DENABLE_ST_OMX_TIZONIA=0" "-DALLOW_KCMP" "-D_WINDOWS" "-D_WIN32_WINNT=0x0A00" "-DWINVER=0x0A00" "-DPIPE_SUBSYSTEM_WINDOWS_USER" "-D_USE_MATH_DEFINES" "-DVC_EXTRALEAN" "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_SECURE_NO_DEPRECATE" "-D_SCL_SECURE_NO_WARNINGS" "-D_SCL_SECURE_NO_DEPRECATE" "-D_ALLOW_KEYWORD_MACROS" "-D_HAS_EXCEPTIONS=0" "-DNOMINMAX" "-DUSE_SSE41" "-DMISSING_64BIT_ATOMICS" "-DHAVE_STRTOF" "-DHAVE_TIMESPEC_GET" "-DHAVE_QSORT_S" "-DHAVE_STRUCT_TIMESPEC" "-DHAVE_ZLIB" "-DHAVE_COMPRESSION" "-DWIN32_LEAN_AND_MEAN" "-DMESA_EXECMEM" "/wd4018" "/wd4056" "/wd4244" "/wd4267" "/wd4305" "/wd4351" "/wd4756" "/wd4800" "/wd4996" "/wd4291" "/wd4146" "/wd4200" "/wd4624" "/wd4309" "/wd4838" "/wd5105" "/we4020" "/we4024" "/we4189" "/Zc:__cplusplus" "/Fdsrc\gallium\winsys/virgl/lib\libvgpu_api.a.p\vgpu_api.c.pdb" /Fosrc/gallium/winsys/virgl/lib/libvgpu_api.a.p/vgpu_api.c.obj "/c" ../src/gallium/winsys/virgl/lib/vgpu_api.c
D:\mvisor-win-vgpu-driver-master\usermode\mesa\include\drm-uapi\drm.h(128): error C2061: syntax error: identifier '__volatile__'
D:\mvisor-win-vgpu-driver-master\usermode\mesa\include\drm-uapi\drm.h(130): error C2059: syntax error: '}'
[870/905] Compiling C object src/gallium/winsys/virgl/drm/libvirgldrm.a.p/virgl_drm_winsys.c.obj
FAILED: src/gallium/winsys/virgl/drm/libvirgldrm.a.p/virgl_drm_winsys.c.obj
"cl" "-Isrc\gallium\winsys/virgl/drm\libvirgldrm.a.p" "-Isrc\gallium\winsys/virgl/drm" "-I..\src\gallium\winsys\virgl\drm" "-Iinclude" "-I..\include" "-Isrc" "-I..\src" "-Isrc\mapi" "-I..\src\mapi" "-Isrc\mesa" "-I..\src\mesa" "-I..\src\gallium\include" "-Isrc\gallium\auxiliary" "-I..\src\gallium\auxiliary" "-Isrc\gallium\drivers" "-I..\src\gallium\drivers" "-Isrc\virtio" "-I..\src\virtio" "-Isrc\gallium\winsys/virgl/common" "-I..\src\gallium\winsys\virgl\common" "-Isubprojects\zlib-1.2.13" "-I..\subprojects\zlib-1.2.13" "-Isrc\compiler\nir" "-I..\src\compiler\nir" "-Isrc\gallium\winsys/virgl/lib" "-I..\src\gallium\winsys\virgl\lib" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/std:c11" "/O2" "/Gw" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DPACKAGE_VERSION=\"23.1.0-devel\"" "-DPACKAGE_BUGREPORT=\"https://gitlab.freedesktop.org/mesa/mesa/-/issues\"" "-DHAVE_OPENGL=1" "-DHAVE_OPENGL_ES_1=0" "-DHAVE_OPENGL_ES_2=0" "-DHAVE_VIRGL" "-DVIDEO_CODEC_VC1DEC=0" "-DVIDEO_CODEC_H264DEC=0" "-DVIDEO_CODEC_H264ENC=0" "-DVIDEO_CODEC_H265DEC=0" "-DVIDEO_CODEC_H265ENC=0" "-DHAVE_WINDOWS_PLATFORM" "-DENABLE_ST_OMX_BELLAGIO=0" "-DENABLE_ST_OMX_TIZONIA=0" "-DALLOW_KCMP" "-D_WINDOWS" "-D_WIN32_WINNT=0x0A00" "-DWINVER=0x0A00" "-DPIPE_SUBSYSTEM_WINDOWS_USER" "-D_USE_MATH_DEFINES" "-DVC_EXTRALEAN" "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_SECURE_NO_DEPRECATE" "-D_SCL_SECURE_NO_WARNINGS" "-D_SCL_SECURE_NO_DEPRECATE" "-D_ALLOW_KEYWORD_MACROS" "-D_HAS_EXCEPTIONS=0" "-DNOMINMAX" "-DUSE_SSE41" "-DMISSING_64BIT_ATOMICS" "-DHAVE_STRTOF" "-DHAVE_TIMESPEC_GET" "-DHAVE_QSORT_S" "-DHAVE_STRUCT_TIMESPEC" "-DHAVE_ZLIB" "-DHAVE_COMPRESSION" "-DWIN32_LEAN_AND_MEAN" "-DMESA_EXECMEM" "/wd4018" "/wd4056" "/wd4244" "/wd4267" "/wd4305" "/wd4351" "/wd4756" "/wd4800" "/wd4996" "/wd4291" "/wd4146" "/wd4200" "/wd4624" "/wd4309" "/wd4838" "/wd5105" "/we4020" "/we4024" "/we4189" "/Zc:__cplusplus" "/Fdsrc\gallium\winsys/virgl/drm\libvirgldrm.a.p\virgl_drm_winsys.c.pdb" /Fosrc/gallium/winsys/virgl/drm/libvirgldrm.a.p/virgl_drm_winsys.c.obj "/c" ../src/gallium/winsys/virgl/drm/virgl_drm_winsys.c
D:\mvisor-win-vgpu-driver-master\usermode\mesa\include\drm-uapi\drm.h(128): error C2061: syntax error: identifier '__volatile__'
D:\mvisor-win-vgpu-driver-master\usermode\mesa\include\drm-uapi\drm.h(130): error C2059: syntax error: '}'
D:\mvisor-win-vgpu-driver-master\usermode\mesa\src\gallium\winsys\virgl\drm\virgl_drm_winsys.h(82): error C2099: initializer is not a constant
[871/905] Compiling C object src/gallium/drivers/virgl/libvirgl.a.p/virgl_video.c.obj
FAILED: src/gallium/drivers/virgl/libvirgl.a.p/virgl_video.c.obj
"cl" "-Isrc\gallium\drivers/virgl\libvirgl.a.p" "-Isrc\gallium\drivers/virgl" "-I..\src\gallium\drivers\virgl" "-Iinclude" "-I..\include" "-Isrc" "-I..\src" "-Isrc\mapi" "-I..\src\mapi" "-Isrc\mesa" "-I..\src\mesa" "-I..\src\gallium\include" "-Isrc\gallium\auxiliary" "-I..\src\gallium\auxiliary" "-Isrc\virtio" "-I..\src\virtio" "-Isubprojects\zlib-1.2.13" "-I..\subprojects\zlib-1.2.13" "-Isrc\compiler\nir" "-I..\src\compiler\nir" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/std:c11" "/O2" "/Gw" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DPACKAGE_VERSION=\"23.1.0-devel\"" "-DPACKAGE_BUGREPORT=\"https://gitlab.freedesktop.org/mesa/mesa/-/issues\"" "-DHAVE_OPENGL=1" "-DHAVE_OPENGL_ES_1=0" "-DHAVE_OPENGL_ES_2=0" "-DHAVE_VIRGL" "-DVIDEO_CODEC_VC1DEC=0" "-DVIDEO_CODEC_H264DEC=0" "-DVIDEO_CODEC_H264ENC=0" "-DVIDEO_CODEC_H265DEC=0" "-DVIDEO_CODEC_H265ENC=0" "-DHAVE_WINDOWS_PLATFORM" "-DENABLE_ST_OMX_BELLAGIO=0" "-DENABLE_ST_OMX_TIZONIA=0" "-DALLOW_KCMP" "-D_WINDOWS" "-D_WIN32_WINNT=0x0A00" "-DWINVER=0x0A00" "-DPIPE_SUBSYSTEM_WINDOWS_USER" "-D_USE_MATH_DEFINES" "-DVC_EXTRALEAN" "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_SECURE_NO_DEPRECATE" "-D_SCL_SECURE_NO_WARNINGS" "-D_SCL_SECURE_NO_DEPRECATE" "-D_ALLOW_KEYWORD_MACROS" "-D_HAS_EXCEPTIONS=0" "-DNOMINMAX" "-DUSE_SSE41" "-DMISSING_64BIT_ATOMICS" "-DHAVE_STRTOF" "-DHAVE_TIMESPEC_GET" "-DHAVE_QSORT_S" "-DHAVE_STRUCT_TIMESPEC" "-DHAVE_ZLIB" "-DHAVE_COMPRESSION" "-DWIN32_LEAN_AND_MEAN" "-DMESA_EXECMEM" "/wd4018" "/wd4056" "/wd4244" "/wd4267" "/wd4305" "/wd4351" "/wd4756" "/wd4800" "/wd4996" "/wd4291" "/wd4146" "/wd4200" "/wd4624" "/wd4309" "/wd4838" "/wd5105" "/we4020" "/we4024" "/we4189" "/Zc:__cplusplus" "-DNO_REGEX" "/Fdsrc\gallium\drivers/virgl\libvirgl.a.p\virgl_video.c.pdb" /Fosrc/gallium/drivers/virgl/libvirgl.a.p/virgl_video.c.obj "/c" ../src/gallium/drivers/virgl/virgl_video.c
../src/gallium/drivers/virgl/virgl_video.c(657): error C2036: 'void *': unknown size
[872/905] Compiling C object src/gallium/drivers/virgl/libvirgl.a.p/virgl_texture.c.obj
FAILED: src/gallium/drivers/virgl/libvirgl.a.p/virgl_texture.c.obj
"cl" "-Isrc\gallium\drivers/virgl\libvirgl.a.p" "-Isrc\gallium\drivers/virgl" "-I..\src\gallium\drivers\virgl" "-Iinclude" "-I..\include" "-Isrc" "-I..\src" "-Isrc\mapi" "-I..\src\mapi" "-Isrc\mesa" "-I..\src\mesa" "-I..\src\gallium\include" "-Isrc\gallium\auxiliary" "-I..\src\gallium\auxiliary" "-Isrc\virtio" "-I..\src\virtio" "-Isubprojects\zlib-1.2.13" "-I..\subprojects\zlib-1.2.13" "-Isrc\compiler\nir" "-I..\src\compiler\nir" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/std:c11" "/O2" "/Gw" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DPACKAGE_VERSION=\"23.1.0-devel\"" "-DPACKAGE_BUGREPORT=\"https://gitlab.freedesktop.org/mesa/mesa/-/issues\"" "-DHAVE_OPENGL=1" "-DHAVE_OPENGL_ES_1=0" "-DHAVE_OPENGL_ES_2=0" "-DHAVE_VIRGL" "-DVIDEO_CODEC_VC1DEC=0" "-DVIDEO_CODEC_H264DEC=0" "-DVIDEO_CODEC_H264ENC=0" "-DVIDEO_CODEC_H265DEC=0" "-DVIDEO_CODEC_H265ENC=0" "-DHAVE_WINDOWS_PLATFORM" "-DENABLE_ST_OMX_BELLAGIO=0" "-DENABLE_ST_OMX_TIZONIA=0" "-DALLOW_KCMP" "-D_WINDOWS" "-D_WIN32_WINNT=0x0A00" "-DWINVER=0x0A00" "-DPIPE_SUBSYSTEM_WINDOWS_USER" "-D_USE_MATH_DEFINES" "-DVC_EXTRALEAN" "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_SECURE_NO_DEPRECATE" "-D_SCL_SECURE_NO_WARNINGS" "-D_SCL_SECURE_NO_DEPRECATE" "-D_ALLOW_KEYWORD_MACROS" "-D_HAS_EXCEPTIONS=0" "-DNOMINMAX" "-DUSE_SSE41" "-DMISSING_64BIT_ATOMICS" "-DHAVE_STRTOF" "-DHAVE_TIMESPEC_GET" "-DHAVE_QSORT_S" "-DHAVE_STRUCT_TIMESPEC" "-DHAVE_ZLIB" "-DHAVE_COMPRESSION" "-DWIN32_LEAN_AND_MEAN" "-DMESA_EXECMEM" "/wd4018" "/wd4056" "/wd4244" "/wd4267" "/wd4305" "/wd4351" "/wd4756" "/wd4800" "/wd4996" "/wd4291" "/wd4146" "/wd4200" "/wd4624" "/wd4309" "/wd4838" "/wd5105" "/we4020" "/we4024" "/we4189" "/Zc:__cplusplus" "-DNO_REGEX" "/Fdsrc\gallium\drivers/virgl\libvirgl.a.p\virgl_texture.c.pdb" /Fosrc/gallium/drivers/virgl/libvirgl.a.p/virgl_texture.c.obj "/c" ../src/gallium/drivers/virgl/virgl_texture.c
../src/gallium/drivers/virgl/virgl_texture.c(189): error C2036: 'void *': unknown size
../src/gallium/drivers/virgl/virgl_texture.c(211): error C2036: 'void *': unknown size
[873/905] Compiling C object src/gallium/drivers/virgl/libvirgl.a.p/virgl_transfer_queue.c.obj
FAILED: src/gallium/drivers/virgl/libvirgl.a.p/virgl_transfer_queue.c.obj
"cl" "-Isrc\gallium\drivers/virgl\libvirgl.a.p" "-Isrc\gallium\drivers/virgl" "-I..\src\gallium\drivers\virgl" "-Iinclude" "-I..\include" "-Isrc" "-I..\src" "-Isrc\mapi" "-I..\src\mapi" "-Isrc\mesa" "-I..\src\mesa" "-I..\src\gallium\include" "-Isrc\gallium\auxiliary" "-I..\src\gallium\auxiliary" "-Isrc\virtio" "-I..\src\virtio" "-Isubprojects\zlib-1.2.13" "-I..\subprojects\zlib-1.2.13" "-Isrc\compiler\nir" "-I..\src\compiler\nir" "-DNDEBUG" "/MD" "/nologo" "/showIncludes" "/utf-8" "/W2" "/std:c11" "/O2" "/Gw" "-D__STDC_CONSTANT_MACROS" "-D__STDC_FORMAT_MACROS" "-D__STDC_LIMIT_MACROS" "-DPACKAGE_VERSION=\"23.1.0-devel\"" "-DPACKAGE_BUGREPORT=\"https://gitlab.freedesktop.org/mesa/mesa/-/issues\"" "-DHAVE_OPENGL=1" "-DHAVE_OPENGL_ES_1=0" "-DHAVE_OPENGL_ES_2=0" "-DHAVE_VIRGL" "-DVIDEO_CODEC_VC1DEC=0" "-DVIDEO_CODEC_H264DEC=0" "-DVIDEO_CODEC_H264ENC=0" "-DVIDEO_CODEC_H265DEC=0" "-DVIDEO_CODEC_H265ENC=0" "-DHAVE_WINDOWS_PLATFORM" "-DENABLE_ST_OMX_BELLAGIO=0" "-DENABLE_ST_OMX_TIZONIA=0" "-DALLOW_KCMP" "-D_WINDOWS" "-D_WIN32_WINNT=0x0A00" "-DWINVER=0x0A00" "-DPIPE_SUBSYSTEM_WINDOWS_USER" "-D_USE_MATH_DEFINES" "-DVC_EXTRALEAN" "-D_CRT_SECURE_NO_WARNINGS" "-D_CRT_SECURE_NO_DEPRECATE" "-D_SCL_SECURE_NO_WARNINGS" "-D_SCL_SECURE_NO_DEPRECATE" "-D_ALLOW_KEYWORD_MACROS" "-D_HAS_EXCEPTIONS=0" "-DNOMINMAX" "-DUSE_SSE41" "-DMISSING_64BIT_ATOMICS" "-DHAVE_STRTOF" "-DHAVE_TIMESPEC_GET" "-DHAVE_QSORT_S" "-DHAVE_STRUCT_TIMESPEC" "-DHAVE_ZLIB" "-DHAVE_COMPRESSION" "-DWIN32_LEAN_AND_MEAN" "-DMESA_EXECMEM" "/wd4018" "/wd4056" "/wd4244" "/wd4267" "/wd4305" "/wd4351" "/wd4756" "/wd4800" "/wd4996" "/wd4291" "/wd4146" "/wd4200" "/wd4624" "/wd4309" "/wd4838" "/wd5105" "/we4020" "/we4024" "/we4189" "/Zc:__cplusplus" "-DNO_REGEX" "/Fdsrc\gallium\drivers/virgl\libvirgl.a.p\virgl_transfer_queue.c.pdb" /Fosrc/gallium/drivers/virgl/libvirgl.a.p/virgl_transfer_queue.c.obj "/c" ../src/gallium/drivers/virgl/virgl_transfer_queue.c
../src/gallium/drivers/virgl/virgl_transfer_queue.c(375): error C2036: 'void *': unknown size
[879/905] Compiling C++ object src/compiler/glsl/libglsl.a.p/builtin_functions.cpp.obj
ninja: build stopped: subcommand failed.
Could not rebuild D:\mvisor-win-vgpu-driver-master\usermode\mesa\build
build finished.
Press any key to continue . . .

**Comment by nooodles2023** [comment]
In c/c++, void* is unknown size, the compiler don't know how to move the pointer like this: void* p=buf; p++;
GCC seems to ignore it or translate it to char*, but MSVC treat it more strictly.
Maybe you could use gcc to compile, or fix the void* to char*

**Comment by Gargazou** [comment]
Thanks.  I got that when I saw the errors.
Can I compile this code in Linux dev environment at all?  It seems Linux would be easier.  Will the "configure" part of the build process realize it needs to cross compile to Windows 10?
Am I stuck using cygwin?

:-|
