### ISSUE TITLE
compile under linux using mingw64 fails

### ISSUE THREAD

**Issue by woecj** [tenclass/mvisor-win-vgpu-driver#7]
I tried to compile under debian bookworm using mingw.
After cloning mesa and patching I tried the command from usermod/build.bat:
`meson setup build -Dbuildtype=release -Dgallium-drivers=virgl -Dgallium-windows-dll-name=MvisorVGPUx64 -Dllvm=disabled -Dprefix=/builddir`
This resulted in the following error:
`meson.build:251:2: ERROR: Problem encountered: swrast vulkan requires gallium swrast`

Are there further preparations to compile under linux?

**Comment by nooodles2023** [comment]
Maybe you could try to compile it on windows

**Comment by woecj** [comment]
Yes, I tried it just before. But also problems with missing things.
I installed VS2019, python
But now, pkg-config is missing - it seems that this program is thought for mingw environment.
Would be useful to have a full description which package have to be available on windows to compile ...

**Comment by woecj** [comment]
Ok, here is the output of the compile:
`start building
mesa install path=c:/Users/hans/vgpu-build
The Meson build system
Version: 1.4.0
Source dir: C:\Users\hans\mvisor-win-vgpu\mvisor-win-vgpu-driver-master\usermode\mesa
Build dir: C:\Users\hans\mvisor-win-vgpu\mvisor-win-vgpu-driver-master\usermode\mesa\build
Build type: native build
Project name: mesa
Project version: 23.1.0-devel
C compiler for the host machine: cl (msvc 19.29.30154 "Microsoft (R) C/C++-Optimierungscompiler Version 19.29.30154 f�r x86")
C linker for the host machine: link link 14.29.30154.0
C++ compiler for the host machine: cl (msvc 19.29.30154 "Microsoft (R) C/C++-Optimierungscompiler Version 19.29.30154 f�r x86")
C++ linker for the host machine: link link 14.29.30154.0
Host machine cpu family: x86
Host machine cpu: x86
Checking if "-mtls-dialect=gnu2" runs: DID NOT COMPILE
Dependency vdpau skipped: feature gallium-vdpau disabled
Found pkg-config: YES (C:\Opt\bin\pkg-config.EXE) 0.26
Found CMake: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE (3.20.21032501)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency libva-win32 found: NO (tried pkgconfig and cmake)
Program C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python found: YES (C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.EXE)

meson.build:847:2: ERROR: Problem encountered: Python (3.x) mako module >= 0.8.0 required to build mesa.

A full log can be found at C:\Users\hans\mvisor-win-vgpu\mvisor-win-vgpu-driver-master\usermode\mesa\build\meson-logs\meson-log.txt`

**Comment by nooodles2023** [comment]
oh~how about just following the err message, flex is needed to be installed.
I haven't gather the env information about compiling usermode driver yet.
If you confused about it, maybe you could use the release building?

**Comment by woecj** [comment]
Ok, I use the build package now (I did not recognise it exists before)
Install in vm runs smooth
I installed virgilrenderer in the host
But when starting vm , I get an error
`[0.000] ../core/configuration.cc:257 LoadObjects() warn: object not found virtio-vgpu virtio-vgpu`
/dev/dri/renderD128 is existing
Do I miss anything more?

**Comment by nooodles2023** [comment]
- class: virtio-vgpu
    memory: 1G
    staging: Yes
    blob: Yes
    node: /dev/dri/renderD128

have you put this in your config?

**Comment by woecj** [comment]
yes, I did

**Comment by nooodles2023** [comment]
You need to add -Dvgpu=true when you compile mvisor

**Comment by woecj** [comment]
After adding this option, the start error vanishes, but the vm crashes on start continuosly (Windows 10 pro)
No error messages from mvisor
I compiled and installed virgilrenderer. Are there additional things to be done beyond installing the dynamic libraries on the host?

**Comment by nooodles2023** [comment]
if the opengl32.dll exists, you don't need to copy again.
Check the device manager if the Mvisor VGPU in system device group worked.

**Comment by woecj** [comment]
Ok, Mvisor VGPU device in system device group is there and no errors in the device infos.
I am unsure if the host system needs more preparation?
- I had to load virtio module on the host to get VM working
- virtio module is loaded by modprobe, but not used by anything
- virglrenderer is installed, installation copies dynamic libraries in the system lib directories, ldconfig registered them
- do I need virgl_test_server ? I can launch it, but nothing happens ...

**Comment by nooodles2023** [comment]
post some info from mvisor and guest vm when you run GPUtest.exe

**Comment by nooodles2023** [comment]
What is virtualrender?

**Comment by woecj** [comment]
I am sorry, I meant virglrenderer
I started GPUtest also by doubleclicking.
![grafik](https://github.com/tenclass/mvisor-win-vgpu-driver/assets/109601524/e3bfe345-330e-4216-afa1-00d56352a92e)
When launching the test, an empty window appears and vanishes immediately

**Comment by nooodles2023** [comment]
> I am sorry, I meant virglrenderer I started GPUtest also by doubleclicking. ![grafik](https://private-user-images.githubusercontent.com/109601524/325126689-e3bfe345-330e-4216-afa1-00d56352a92e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDUwNjMsIm5iZiI6MTcxMzk0NDc2MywicGF0aCI6Ii8xMDk2MDE1MjQvMzI1MTI2Njg5LWUzYmZlMzQ1LTMzMGUtNDIxNi1hZmExLTAwZDU2MzUyYTkyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQwNzQ2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGIxNzk3YmVmNzVlZThmY2UxMDQ5M2E4MzI5ZDRjZjFhNTg2M2NiYTY3M2VlMTRhNGUwMmY1ZTliYjlkOGRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t6ccR9nSPCCyOEqVlMvMvHWosGi5mrbFnHRVz-bX560) When launching the test, an empty window appears and vanishes immediately

select test with opengl4

**Comment by nooodles2023** [comment]
> There are no infos from mvisor or guest when running GPUtest.exe:
> 
> * mvisor on host does not give any message while running GPUtest
> * in VM, also no message in cmdline window, just test window appears and vanishes w/o message
>   Can I use options to increase the verbosity?
> 
> In Systeminfo, I found the following line: `virtualrender VirtualRender c:\windows\system32\driverstore\filerepository\vrd.inf_amd64_81fbd405ff2470fc\vrd.sys Kerneldriver No Manuell Ended OK Ignore No No`

the driver you showed was not the vgpu driver

**Comment by woecj** [comment]
That is what I see in the device manager:
![grafik](https://github.com/tenclass/mvisor-win-vgpu-driver/assets/109601524/44d4a8a2-daec-495d-9447-b4fca3c030be)

**Comment by nooodles2023** [comment]
have you got any  output about opengl in mvisor output?

**Comment by woecj** [comment]
Nothing concerning graphics, only messages concerning sound not working:
`ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
[95966.913] ../gui/sdl/viewer.cc:232 OnPlayback() warn: snd_pcm_open error: No such file or directory
`

**Comment by woecj** [comment]
Here is the output of dbgview:
![grafik](https://github.com/tenclass/mvisor-win-vgpu-driver/assets/109601524/c5945742-fadf-47a0-ba8d-f0b1d2d356a3)

**Comment by nooodles2023** [comment]
> Here is the output of dbgview: ![grafik](https://private-user-images.githubusercontent.com/109601524/325251175-c5945742-fadf-47a0-ba8d-f0b1d2d356a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMTU3MDEsIm5iZiI6MTcxNDAxNTQwMSwicGF0aCI6Ii8xMDk2MDE1MjQvMzI1MjUxMTc1LWM1OTQ1NzQyLWZhZGYtNDdhMC1iYThkLWYwYjFkMmQzNTZhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwMzIzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTA3NGNlMjE5YWU0NzA4NTA1MWUyMmRjMTM2ZTE4OWQwNTRjNzU2NjQ5ZmUwYTcwMGE2NDZiNjlmZmIzNTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s0tEIfzzaJQuEVi2O6_cc5_GZMECI-tRXOYCgpHrTH8) And here the output when running glview: ![grafik](https://private-user-images.githubusercontent.com/109601524/325252484-afcfedcb-4b42-4403-8c3e-8f9a3986c064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMTU3MDEsIm5iZiI6MTcxNDAxNTQwMSwicGF0aCI6Ii8xMDk2MDE1MjQvMzI1MjUyNDg0LWFmY2ZlZGNiLTRiNDItNDQwMy04YzNlLThmOWEzOTg2YzA2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwMzIzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTJhZWE0Y2NmZDcyYzhiZjFhNTk3YTVmYzMzMzg4YmQ3OTZhNTc5MzliYzQ1Mzc0MzY1NDRiZmVjMGJmYzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sl_tkCyqVPV_m2gB8aa95UkTQcp8nkSRxeCGpyeYNng)
> 
> Maybe my experience is connected to issue #2 ?

Yes~, the number 31 was the windows system error code which returned from getlasterror().
It failed to call DeviceIoControl to get caps from driver.
Have you run GPUTest.exe as administrator? 
There were something wrong with the connection method between dll and driver.

**Comment by nooodles2023** [comment]
> Here is the output of dbgview: ![grafik](https://private-user-images.githubusercontent.com/109601524/325251175-c5945742-fadf-47a0-ba8d-f0b1d2d356a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMTU3MDEsIm5iZiI6MTcxNDAxNTQwMSwicGF0aCI6Ii8xMDk2MDE1MjQvMzI1MjUxMTc1LWM1OTQ1NzQyLWZhZGYtNDdhMC1iYThkLWYwYjFkMmQzNTZhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwMzIzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTA3NGNlMjE5YWU0NzA4NTA1MWUyMmRjMTM2ZTE4OWQwNTRjNzU2NjQ5ZmUwYTcwMGE2NDZiNjlmZmIzNTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s0tEIfzzaJQuEVi2O6_cc5_GZMECI-tRXOYCgpHrTH8) And here the output when running glview: ![grafik](https://private-user-images.githubusercontent.com/109601524/325252484-afcfedcb-4b42-4403-8c3e-8f9a3986c064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMTU3MDEsIm5iZiI6MTcxNDAxNTQwMSwicGF0aCI6Ii8xMDk2MDE1MjQvMzI1MjUyNDg0LWFmY2ZlZGNiLTRiNDItNDQwMy04YzNlLThmOWEzOTg2YzA2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwMzIzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTJhZWE0Y2NmZDcyYzhiZjFhNTk3YTVmYzMzMzg4YmQ3OTZhNTc5MzliYzQ1Mzc0MzY1NDRiZmVjMGJmYzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sl_tkCyqVPV_m2gB8aa95UkTQcp8nkSRxeCGpyeYNng)
> 
> Maybe my experience is connected to issue #2 ?

Yes~, the number 31 was the windows system error code which returned from getlasterror().
It failed to call DeviceIoControl to get caps from driver.
Have you run GPUTest.exe as administrator? 
There were something wrong with the connection method between dll and driver.

**Comment by woecj** [comment]
yes, I tried to run GPUTest as administrator.
The result is the same.
Messages in Dbgview are absolute identical - See result screen shot above.
How to solve the problem?

**Comment by woecj** [comment]
Ok, here is the output of dbgview with kernel output enabled:
![grafik](https://github.com/tenclass/mvisor-win-vgpu-driver/assets/109601524/7f8b4d94-b1c8-4bf2-a3e5-cacc2091655e)
Remark: GPUtest was started as normal user, did not start in administrator mode

**Comment by nooodles2023** [comment]
![image](https://github.com/tenclass/mvisor-win-vgpu-driver/assets/29591526/ef7770bd-5af6-420e-be4b-6498d74386b9)
choose like this, and restart the dbgview

**Comment by woecj** [comment]
Here the output again, with kernel messages enabled (was also in the previos attempt)
![grafik](https://github.com/tenclass/mvisor-win-vgpu-driver/assets/109601524/1dcaff75-a6f5-481d-801b-acd2308b1761)
GPUtest was started as normal user, did not start in administrator mode

**Comment by nooodles2023** [comment]
> Here the output again, with kernel messages enabled (was also in the previos attempt) ![grafik](https://private-user-images.githubusercontent.com/109601524/325542926-1dcaff75-a6f5-481d-801b-acd2308b1761.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzU5NDYsIm5iZiI6MTcxNDAzNTY0NiwicGF0aCI6Ii8xMDk2MDE1MjQvMzI1NTQyOTI2LTFkY2FmZjc1LWE2ZjUtNDgxZC04MDFiLWFjZDIzMDhiMTc2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwOTAwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Mjg1OWMyMGRjMmNmMmViNDllNWNkNzBmNzAxODlhMDA2MGMxYjg5MjkyNWZmMDE3ZDcyY2I1YjNhMWQ5OGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AZ8OmvX8YlQsb_q_qcjRCbw1BoGstscEGIJ1t41Fx6I) GPUtest was started as normal user, did not start in administrator mode

There isn't any info from kernel, try to stop catching user space, only catch kernel space

**Comment by woecj** [comment]
I disabled user space, then there is no capture output!

**Comment by nooodles2023** [comment]
> I disabled user space, only kernel space is enabled, then there is no capture output!

what is your guest os version, dbgview need be run as admin too

**Comment by woecj** [comment]
Guest is Windows10 Pro
Version	10.0.19042 Build 19042

**Comment by nooodles2023** [comment]
> Guest is Windows10 Pro Version 10.0.19042 Build 19042
> 
> dbgview was run as Administrator

My guest env is 21H2(19044), it works well in the production env.
I'd like to fix this bug but I can't find a way to reproduce the error=31

**Comment by nooodles2023** [comment]
> so, should I upgrade to 21h2 ?

or you may need to wait for me to fix it, maybe next weekend

**Comment by woecj** [comment]
ok, would be nice if you can fix the bug. Thanks and I wish you success!

**Comment by nooodles2023** [comment]
buddy, why do you want to test this vgpu? for interest?

**Comment by woecj** [comment]
I want to use some apps within the guest requesting opengl.
Your mvisor implementation looks like very small and shows very good response behavior.
So if your solution is stable and supplies opengl, I could possible switch from other solutions I use up to now (vmware is currently the only vm having really working opengl to my knowledge)

**Comment by nooodles2023** [comment]
Can vmware support opengl4 in windows guest vm?
I have tested opengl4 in virtualbox/vmware,  but neither of them could work.

**Comment by woecj** [comment]
vmware has at least opengl 3.2 (I don't remember if it is 4, I will check it)
virtualbox has opengl 3.x , but buggy - some crucial functions do not work

**Comment by woecj** [comment]
Tested it also using Windows10 21H2 19044: result is the same not working, same behavior!
Host: Linux debian bookworm on AMD Ryzen 7 5800X 8-core, KDE Plasma version 5.27.5
Nvidia graphics GeForce RTX 3060, Nvidia driver, version 525.147.05

**Comment by nooodles2023** [comment]
> Tested it also using Windows10 21H2 19044: result is the same not working, same behavior! Host: Linux debian bookworm on AMD Ryzen 7 5800X 8-core, KDE Plasma version 5.27.5 Nvidia graphics GeForce RTX 3060, Nvidia driver, version 525.147.05

would you mind publish your qcow2 file on the cloud where I can download to test?

**Comment by nooodles2023** [comment]
> vmware has at least opengl 4.1 virtualbox has opengl 4.1 also , but buggy - some crucial functions do not work (experimental status)
> 
> Is the vgpu driver also useable in Qemu?

no, it's not for qemu.
GPUtest.exe can be run  with open4.1 test on win10 guest vm using vmware?

**Comment by nooodles2023** [comment]
> 1. publishing qcow2: im I am not shure if it is it worth to transfer such big file (~ 17GB)?
> 2. yes GPUtest is working in vmware with 4.1 tests!

what's the version of vmware? Would mind post the screenshot when Gputest working on vmware?

**Comment by woecj** [comment]
vmware workstation 16
![grafik](https://github.com/tenclass/mvisor-win-vgpu-driver/assets/109601524/0eb80575-fb59-4e15-82f5-ef235440277b)

**Comment by nooodles2023** [comment]
> vmware workstation 16 ![grafik](https://private-user-images.githubusercontent.com/109601524/325963344-f6ee158b-877f-4190-83b2-bd4ed79e4d20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzE3NjUsIm5iZiI6MTcxNDEzMTQ2NSwicGF0aCI6Ii8xMDk2MDE1MjQvMzI1OTYzMzQ0LWY2ZWUxNThiLTg3N2YtNDE5MC04M2IyLWJkNGVkNzllNGQyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQxMTM3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDM3NGQ3MjU4NmFhMjMzZTI2NGZiNzkwZjhlMzVhZjU3MjI5ZGY3MGViNDQwODdkOWRlYzQ0NDc1NDhkYmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ozc1YT7u7UOANUmQIlEZ7B4E1PXn15koYC9icE_Iqzc)

thank you~
Does virtual box support it?

**Comment by woecj** [comment]
Yes, virtualbox also support it - see enclosed sceenshot:
![grafik](https://github.com/tenclass/mvisor-win-vgpu-driver/assets/109601524/b8b5d81d-a146-44f4-b603-50805fd6b598)
